### ISSUE TITLE
第13章 ユーザーのマイクロポスト

### ISSUE THREAD

**Issue by saran12345678** [saran12345678/RubyonRailsTutorial#13]
### RailsコンソールでMicropost.newを実行し、インスタンスを変数micropostに代入してください。その後、user_idに最初のユーザーのidを、contentに "Lorem ipsum" をそれぞれ代入してみてください。この時点では、 micropostオブジェクトのマジックカラムであるcreated_atとupdated_atには何が入っているでしょうか?
```
irb(main):001> Micropost.new
=> #<Micropost:0x00007f54e5a67868 id: nil, content: nil, user_id: nil, created_at: nil, updated_at: nil>
irb(main):002> micropost = Micropost.new
=> #<Micropost:0x00007f54e6189ec0 id: nil, content: nil, user_id: nil, created_at: nil, updated_at: nil>
irb(main):003> micropost.user_id = User.first.id
  User Load (2.7ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> 1
irb(main):004> micropost.content = "Lorem ipsum"
=> "Lorem ipsum"
irb(main):005> micropost.created_at
=> nil
irb(main):006> micropost.updated_at
=> nil
```

### 先ほど作ったオブジェクトを使って、micropost.userを実行してみましょう。どのような結果が返ってくるでしょうか? また、micropost.user.nameを実行した場合の結果はどうなるでしょうか?

```
irb(main):007> micropost.user
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
=> 
#<User:0x00007f54e61e7a98
 id: 1,
 name: "Example User",
 email: "example@railstutorial.org",
 created_at: Tue, 03 Sep 2024 09:59:16.317069000 UTC +00:00,
 updated_at: Wed, 04 Sep 2024 03:34:08.697385000 UTC +00:00,
 password_digest: "[FILTERED]",
 remember_digest: "$2a$12$e9Tm3nUhAjrVTY.J.fkvduYSQGgLJv3rDxavFqe/dpOxAOtS32VZC",
 admin: true,
 activation_digest: "$2a$12$osFSOju3WY4S9ASY3b58VOi8PZj.63xRdCF/ypHCfl44YEv3sAUC.",
 activated: true,
 activated_at: Tue, 03 Sep 2024 09:59:16.076756000 UTC +00:00,
 reset_digest: "$2a$12$L09RJbX43tcLmnEFAn44.O6Na2eltZS8QDXWK/ZrfjboWxb3xwhR6",
 reset_sent_at: Wed, 04 Sep 2024 03:34:08.697068000 UTC +00:00>
irb(main):008> micropost.user.name
=> "Example User"
```

### 先ほど作ったmicropostオブジェクトをデータベースに保存してみましょう。この時点でもう一度マジックカラムの内容を調べてみましょう。今度はどのような値が入っているでしょうか?
created_at, updated_atに値が入った。
```
irb(main):009> micropost.save
  TRANSACTION (0.1ms)  begin transaction
  Micropost Create (10.5ms)  INSERT INTO "microposts" ("content", "user_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["content", "Lorem ipsum"], ["user_id", 1], ["created_at", "2024-09-04 11:33:11.215273"], ["updated_at", "2024-09-04 11:33:11.215273"]]
  TRANSACTION (25.8ms)  commit transaction
=> true
irb(main):010> micropost
=> #<Micropost:0x00007f54e6189ec0 id: 1, content: "Lorem ipsum", user_id: 1, created_at: Wed, 04 Sep 2024 11:33:11.215273000 UTC +00:00, updated_at: Wed, 04 Sep 2024 11:33:11.215273000 UTC +00:00>
```

**Comment by saran12345678** [comment]
### Railsコンソールを開き、user_idとcontentが空になっているmicropostオブジェクトを作ってみてください。このオブジェクトに対してvalid?を実行すると、失敗することを確認してみましょう。また、生成されたエラーメッセージにはどんな内容が書かれているでしょうか?
```
irb(main):001> micropost = Micropost.new
=> #<Micropost:0x00007641792ee128 id: nil, content: nil, user_id: nil, created_at: nil, updated_at: nil>
irb(main):002> micropost.valid?
=> false
irb(main):003> micropost.errors.full_messages
=> ["User must exist", "User can't be blank", "Content can't be blank"]
```

### コンソールを開き、今度はuser_idが空でcontentが141文字以上のmicropostオブジェクトを作ってみてください。このオブジェクトに対してvalid?を実行すると、失敗することを確認してみましょう。また、生成されたエラーメッセージにはどんな内容が書かれているでしょうか?
```
irb(main):004> micropost.user_id = ""
=> ""
irb(main):005> micropost.content = "a" * 141
=> "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
irb(main):006> micropost.valid?
=> false
irb(main):007> micropost.errors.full_messages
=> ["User must exist", "User can't be blank", "Content is too long (maximum is 140 characters)"]
```

**Comment by saran12345678** [comment]
### データベースにいる最初のユーザーを変数userに代入してください。そのuserオブジェクトを使ってmicropost = user.microposts.create(content: "Lorem ipsum")を実行すると、どのような結果が得られるでしょうか?
Micropostテーブルに登録が行われる
```
irb(main):001> user = User.first
  User Load (0.1ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> 
#<User:0x000076048f61d348
...
irb(main):002> micropost = user.microposts.create(content: "Lorem ipsum")
  TRANSACTION (0.0ms)  begin transaction
  Micropost Create (0.5ms)  INSERT INTO "microposts" ("content", "user_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["content", "Lorem ipsum"], ["user_id", 1], ["created_at", "2024-09-04 12:09:04.353495"], ["updated_at", "2024-09-04 12:09:04.353495"]]
  TRANSACTION (26.0ms)  commit transaction
=> #<Micropost:0x000076048f4161a8 id: 2, content: "Lorem ipsum", user_id: 1, created_at: Wed, 04 Sep 2024 12:09:04.353495000 UTC +00:00, updated_at: Wed, 04 Sep 2024 12:09:04.353495000 UTC +00:00>
```

### 先ほどの演習課題で、データベース上に新しいマイクロポストが追加されたはずです。user.microposts.find(micropost.id)を実行して、本当に追加されたのかを確かめてみましょう。また、先ほど実行したmicropost.idの部分をmicropostに変更すると、結果はどうなるでしょうか?
Micropostのレコードが取得できる
idではなくmicropostに変更するとエラーが発生する
```
=> #<Micropost:0x000076048f4161a8 id: 2, content: "Lorem ipsum", user_id: 1, created_at: Wed, 04 Sep 2024 12:09:04.353495000 UTC +00:00, updated_at: Wed, 04 Sep 2024 12:09:04.353495000 UTC +00:00>
irb(main):003> user.microposts.find(micropost.id)
  Micropost Load (0.2ms)  SELECT "microposts".* FROM "microposts" WHERE "microposts"."user_id" = ? AND "microposts"."id" = ? LIMIT ?  [["user_id", 1], ["id", 2], ["LIMIT", 1]]
=> #<Micropost:0x000076048f0e9110 id: 2, content: "Lorem ipsum", user_id: 1, created_at: Wed, 04 Sep 2024 12:09:04.353495000 UTC +00:00, updated_at: Wed, 04 Sep 2024 12:09:04.353495000 UTC +00:00>
irb(main):004> user.microposts.find(micropost)
/usr/local/rvm/gems/default/gems/activerecord-7.0.4.3/lib/active_record/relation/finder_methods.rb:466:in `find_one': You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`. (ArgumentError)

          raise ArgumentError, <<-MSG.squish
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### user == micropost.userを実行した結果はどうなるでしょうか? また、user.microposts.first == micropost を実行した結果はどうなるでしょうか? それぞれ確認してみてください。
どちらもTrueとなる　※firstを取得してしまうと、前演習の登録結果が取得されるため、secondとして取得を行う
```
irb(main):005> user == micropost.user
=> true
irb(main):006> user.microposts.first == micropost
  Micropost Load (0.2ms)  SELECT "microposts".* FROM "microposts" WHERE "microposts"."user_id" = ? ORDER BY "microposts"."id" ASC LIMIT ?  [["user_id", 1], ["LIMIT", 1]]
=> false
irb(main):007> user.microposts.second == micropost
  Micropost Load (0.2ms)  SELECT "microposts".* FROM "microposts" WHERE "microposts"."user_id" = ? ORDER BY "microposts"."id" ASC LIMIT ? OFFSET ?  [["user_id", 1], ["LIMIT", 1], ["OFFSET", 1]]
=> true
```

**Comment by saran12345678** [comment]
### Micropost.first.created_atの実行結果と、Micropost.last.created_atの実行結果を比べてみましょう。
LastよりFirstの方が作成日時が新しい
```
irb(main):001> Micropost.first.created_at
  Micropost Load (2.3ms)  SELECT "microposts".* FROM "microposts" ORDER BY "microposts"."created_at" DESC LIMIT ?  [["LIMIT", 1]]
=> Wed, 04 Sep 2024 12:09:04.353495000 UTC +00:00
irb(main):002> Micropost.last.created_at
  Micropost Load (0.2ms)  SELECT "microposts".* FROM "microposts" ORDER BY "microposts"."created_at" ASC LIMIT ?  [["LIMIT", 1]]
=> Wed, 04 Sep 2024 11:33:11.215273000 UTC +00:00
```

### Micropost.firstを実行したときに発行されるSQL文はどうなっているでしょうか? 同様にして、Micropost.lastの場合はどうなっているでしょうか?（ヒント: それぞれをコンソール上で実行したときに表示される文字列が、SQL文になります。）
Firstを取得する際には作成日時の降順で先頭を取得している。
→最新のレコードを取得している
Lastを取得する際には作成日時の昇順で先頭を取得している。
→最古のれこーどを取得している
```
irb(main):003> Micropost.first
  Micropost Load (0.1ms)  SELECT "microposts".* FROM "microposts" ORDER BY "microposts"."created_at" DESC LIMIT ?  [["LIMIT", 1]]
=> #<Micropost:0x00007b440b53a500 id: 2, content: "Lorem ipsum", user_id: 1, created_at: Wed, 04 Sep 2024 12:09:04.353495000 UTC +00:00, updated_at: Wed, 04 Sep 2024 12:09:04.353495000 UTC +00:00>
irb(main):004> Micropost.last
  Micropost Load (0.1ms)  SELECT "microposts".* FROM "microposts" ORDER BY "microposts"."created_at" ASC LIMIT ?  [["LIMIT", 1]]
=> #<Micropost:0x00007b440b4d8a30 id: 1, content: "Lorem ipsum", user_id: 1, created_at: Wed, 04 Sep 2024 11:33:11.215273000 UTC +00:00, updated_at: Wed, 04 Sep 2024 11:33:11.215273000 UTC +00:00>
```

### データベース上の最初のユーザーを変数userに代入してください。そのuserオブジェクトが最初に投稿したマイクロポストのidはいくつでしょうか? 次に、destroyメソッドを使ってそのuserオブジェクトを削除してみてください。削除すると、そのuserに紐付いていたマイクロポストも削除されていることをMicropost.findで確認してみましょう。
```
irb(main):005> user = User.first
  User Load (3.1ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> 
#<User:0x00007b440aa1d500
...
irb(main):007> user.microposts.last
  Micropost Load (5.9ms)  SELECT "microposts".* FROM "microposts" WHERE "microposts"."user_id" = ? ORDER BY "microposts"."created_at" ASC LIMIT ?  [["user_id", 1], ["LIMIT", 1]]
=> #<Micropost:0x00007b440b7953e0 id: 1, content: "Lorem ipsum", user_id: 1, created_at: Wed, 04 Sep 2024 11:33:11.215273000 UTC +00:00, updated_at: Wed, 04 Sep 2024 11:33:11.215273000 UTC +00:00>
irb(main):008> user.destroy
  TRANSACTION (0.1ms)  begin transaction
  Micropost Load (0.2ms)  SELECT "microposts".* FROM "microposts" WHERE "microposts"."user_id" = ? ORDER BY "microposts"."created_at" DESC  [["user_id", 1]]
  Micropost Destroy (3.4ms)  DELETE FROM "microposts" WHERE "microposts"."id" = ?  [["id", 2]]
  Micropost Destroy (0.1ms)  DELETE FROM "microposts" WHERE "microposts"."id" = ?  [["id", 1]]
  User Destroy (2.5ms)  DELETE FROM "users" WHERE "users"."id" = ?  [["id", 1]]
  TRANSACTION (27.9ms)  commit transaction
=> 
#<User:0x00007b440aa1d500
 id: 1,
 name: "Example User",
 email: "example@railstutorial.org",
 created_at: Tue, 03 Sep 2024 09:59:16.317069000 UTC +00:00,
 updated_at: Wed, 04 Sep 2024 03:34:08.697385000 UTC +00:00,
 password_digest: "[FILTERED]",
 remember_digest: "$2a$12$e9Tm3nUhAjrVTY.J.fkvduYSQGgLJv3rDxavFqe/dpOxAOtS32VZC",
 admin: true,
 activation_digest: "$2a$12$osFSOju3WY4S9ASY3b58VOi8PZj.63xRdCF/ypHCfl44YEv3sAUC.",
 activated: true,
 activated_at: Tue, 03 Sep 2024 09:59:16.076756000 UTC +00:00,
 reset_digest: "$2a$12$L09RJbX43tcLmnEFAn44.O6Na2eltZS8QDXWK/ZrfjboWxb3xwhR6",
 reset_sent_at: Wed, 04 Sep 2024 03:34:08.697068000 UTC +00:00>
irb(main):009> Micropost.find(id: 1)
  Micropost Load (0.2ms)  SELECT "microposts".* FROM "microposts" WHERE "microposts"."id" = ? ORDER BY "microposts"."created_at" DESC LIMIT ?  [["id", nil], ["LIMIT", 1]]
/usr/local/rvm/gems/default/gems/activerecord-7.0.4.3/lib/active_record/relation/finder_methods.rb:381:in `raise_record_not_found_exception!': Couldn't find Micropost with 'id'={:id=>1} (ActiveRecord::RecordNotFound)
```

**Comment by saran12345678** [comment]
### [7.3.3](https://railstutorial.jp/chapters/sign_up?version=7.0#sec-signup_error_messages)で軽く説明したように、今回ヘルパーメソッドとして使ったtime_ago_in_wordsメソッドは、Railsコンソールのhelperオブジェクトから呼び出すことができます。このhelperオブジェクトのtime_ago_in_wordsメソッドを使って、3.weeks.agoや6.months.agoを実行してみましょう。
```
irb(main):004> helper.time_ago_in_words(3.weeks.ago)
=> "21 days"
irb(main):005> helper.time_ago_in_words(6.months.ago)
=> "6 months"
```

### helper.time_ago_in_words(1.year.ago)と実行すると、どういった結果が返ってくるでしょうか?
```
irb(main):006> helper.time_ago_in_words(1.year.ago)
=> "about 1 year"
```

### micropostsオブジェクトのクラスは何でしょうか? （ヒント: [リスト 13.24](https://railstutorial.jp/chapters/user_microposts?version=7.0#code-user_show_microposts_instance)内のコードを参考に、まずはpaginate(page: nil)でオブジェクトを取得し、その後classメソッドを呼び出してみましょう。）
```
irb(main):009> user = User.first
  User Load (2.4ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> 
#<User:0x00007df3dab668a8
...
irb(main):010> val = user.microposts.paginate(page: nil)
  Micropost Load (0.6ms)  SELECT "microposts".* FROM "microposts" WHERE "microposts"."user_id" = ? ORDER BY "microposts"."created_at" DESC LIMIT ? OFFSET ?  [["user_id", 1], ["LIMIT", 30], ["OFFSET", 0]]
=> []
irb(main):011> val.class
=> Micropost::ActiveRecord_AssociationRelation
```

**Comment by saran12345678** [comment]
### (1..10).to_a.take(6)というコードの実行結果を推測できますか? 推測した値が合っているかどうか、実際にコンソールを使って確認してみましょう。
1から6までが出力される
```
irb(main):001> (1..10).to_a.take(6)
=> [1, 2, 3, 4, 5, 6]
```
正しくは1から6までの配列が出力される　でした。

### 上の演習にあったto_aメソッドの部分は本当に必要でしょうか? 確かめてみてください。
出力結果が同じであるため、to_aメソッドは必要ないと判断
```
irb(main):002> (1..10).take(6)
=> [1, 2, 3, 4, 5, 6]
```

### Fakerはlorem ipsum以外にも、非常に多種多様の事例に対応しています。[Fakerのドキュメント](https://github.com/stympy/faker)（英語）を眺めながら画面に出力する方法を学び、実際に架空の[大学名](https://github.com/faker-ruby/faker/blob/master/doc/default/university.md)や[Hipster Ipsum](https://github.com/faker-ruby/faker/blob/master/doc/default/hipster.md)や[Chuck Norris facts](https://github.com/faker-ruby/faker/blob/master/doc/default/chuck_norris.md)（参考: [チャック・ノリスの真実](https://ja.wikipedia.org/wiki/%E3%83%81%E3%83%A3%E3%83%83%E3%82%AF%E3%83%BB%E3%83%8E%E3%83%AA%E3%82%B9%E3%83%BB%E3%83%95%E3%82%A1%E3%82%AF%E3%83%88)）を画面に出力してみましょう。
```
irb(main):003> Faker::University.name
=> "Dicki Academy"
irb(main):004> Faker::Hipster.words(number: 5)
=> ["Thundercats", "bitters", "humblebrag", "locavore", "Godard"]
irb(main):005> Faker::ChuckNorris.fact
=> "Chuck Norris can access private methods."
```

**Comment by saran12345678** [comment]
### [リスト 13.29](https://railstutorial.jp/chapters/user_microposts?version=7.0#code-user_profile_test)にある2つの'h1'のテストが正しいか確かめるため、該当するアプリケーション側のコードをコメントアウトしてみましょう。テストが green から red に変わることを確認してみてください。
show.html.erbにてh1タグをコメントアウトした
```
# Running:

..........................................................F...................

Finished in 5.701767s, 13.6800 runs/s, 46.6522 assertions/s.

  1) Failure:
UsersProfileTest#test_profile_display [/workspaces/sample_app/test/integration/users_profile_test.rb:14]:
Expected at least 1 element matching "h1", found 0..
Expected 0 to be >= 1.

78 runs, 266 assertions, 1 failures, 0 errors, 0 skips
```

### [リスト 13.29](https://railstutorial.jp/chapters/user_microposts?version=7.0#code-user_profile_test)にあるテストを変更して、will_paginateが1回だけ表示されていることをテストしてみましょう。（ヒント: [表 5.2](https://railstutorial.jp/chapters/filling_in_the_layout?version=7.0#table-assert_select)を参考にしてください。）
```
    assert_select 'div.pagination', count: 1
```
```
Finished in 5.672112s, 13.7515 runs/s, 58.1794 assertions/s.
```

**Comment by saran12345678** [comment]
### なぜUsersコントローラ内にあるlogged_in_userフィルターを残したままにするとマズイのでしょうか? 考えてみてください。
アクセスできるlogged_in_userが2つ以上になる場合、どちらを呼び出して良いかわからない。
また、同じ名称のメソッドを2つ以上定義できないはず。

**Comment by saran12345678** [comment]
### Homeページをリファクタリングして、if-else文の分岐のそれぞれに対してパーシャルを作ってみましょう。
```ruby
<% if logged_in? %>
  <%= render 'static_pages/home_logged_in' %>
<% else %>
  <%= render 'static_pages/home_not_logged_in' %>
<% end %>
```

### マイクロポストを投稿した直後に、ブラウザの更新ボタンを押すとエラーが表示されます。なぜエラーが表示されるのでしょうか？その原因を考えてみましょう。
何度も試したがエラーは発生しなかった。

### もし上記の現象に対応するとしたら、どんな対応方法があるでしょうか？その対応方法を考えてみましょう。（ヒント: 様々な対応方法がありますが、対応方法によっては今後の実装に支障が出ることがあります。ここでは対応方法のアイデア出しに留めておきましょう。）
エラーが発生しないため検討できず。

**Comment by saran12345678** [comment]
### 新しく実装したマイクロポストの投稿フォームを使って、実際にマイクロポストを投稿してみましょう。Railsサーバーのログ内にあるINSERT文では、どういった内容をデータベースに送っているでしょうか? 確認してみてください。
特別な内容は送っていない
```
Micropost Create (0.5ms)  INSERT INTO "microposts" ("content", "user_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["content", "testaaa"], ["user_id", 1], ["created_at", "2024-09-05 05:19:27.613579"], ["updated_at", "2024-09-05 05:19:27.613579"]]
```

### コンソールを開き、user変数にデータベース上の最初のユーザーを代入してみましょう。その後、Micropost.where("user_id = ?", user.id)とuser.microposts、そしてuser.feedをそれぞれ実行してみて、実行結果がすべて同じであることを確認してみてください。（ヒント: ==で比較すると結果が同じかどうか簡単に判別できます。）
```
irb(main):001> user = User.first
  User Load (0.1ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> 
#<User:0x00007fbb094607f0
...
irb(main):002> Micropost.where("user_id = ?", user.id) == user.feed
=> true
```

**Comment by saran12345678** [comment]
### マイクロポストを作成し、その後、作成したマイクロポストを削除してみましょう。次に、Railsサーバーのログを開いて、DELETE文の内容を確認してみてください。
```
Micropost Destroy (0.3ms)  DELETE FROM "microposts" WHERE "microposts"."id" = ?  [["id", 309]]
  ↳ app/controllers/microposts_controller.rb:17:in `destroy'
```

### [リスト 13.56](https://railstutorial.jp/chapters/user_microposts?version=7.0#code-microposts_destroy_action)の2つのリダイレクトを、redirect_back_or_to(root_url, status: :see_other)と1行で置き換えてもうまく動くことを、ブラウザを使って確認してみましょう。これは、参照元URLがnilである場合は指定のURLにリダイレクトします。
ポストの削除を行っても問題なくリダイレクトされた
![スクリーンショット 2024-09-05 14 38 28](https://github.com/user-attachments/assets/d82e0882-0e1e-4c22-a64b-370326af5e94)

**Comment by saran12345678** [comment]
### [リスト 13.59](https://railstutorial.jp/chapters/user_microposts?version=7.0#code-microposts_interface_test)で示した4つのテスト項目が正しく動いているかをテスト項目ごとに確認してみましょう。具体的には、対応するアプリケーション側のコードをコメントアウトし、テストが red になることを確認し、元に戻すと green になることを確認してみましょう。
```
# Running:

.............F.........................................................................

Finished in 5.825198s, 14.9351 runs/s, 59.3971 assertions/s.

  1) Failure:
MicropostsInterfaceTest#test_should_create_a_micropost_on_valid_submission [/workspaces/sample_app/test/integration/microposts_interface_test.rb:31]:
Expected response to be a <3XX: redirect>, but was a <204: No Content>
Response body: 
```
```
# Running:

..........................E............................................................

Finished in 5.923086s, 14.6883 runs/s, 58.4155 assertions/s.

  1) Error:
MicropostsInterfaceTest#test_should_show_errors_but_not_create_micropost_on_invalid_submission:
NoMethodError: undefined method `document' for nil:NilClass
    test/integration/microposts_interface_test.rb:22:in `block in <class:MicropostsInterfaceTest>'

87 runs, 346 assertions, 0 failures, 1 errors, 0 skips
```
```
# Running:

.........F.............................................................................

Finished in 5.919239s, 14.6978 runs/s, 58.7913 assertions/s.

  1) Failure:
MicropostsInterfaceTest#test_should_be_able_to_delete_own_micropost [/workspaces/sample_app/test/integration/microposts_interface_test.rb:43]:
"Micropost.count" didn't change by -1.
Expected: 36
  Actual: 37

87 runs, 348 assertions, 1 failures, 0 errors, 0 skips
```
```
# Running:

............................................................F..........................

Finished in 5.845794s, 14.8825 runs/s, 59.0168 assertions/s.

  1) Failure:
MicropostsInterfaceTest#test_should_create_a_micropost_on_valid_submission [/workspaces/sample_app/test/integration/microposts_interface_test.rb:28]:
"Micropost.count" didn't change by 1.
Expected: 38
  Actual: 37

87 runs, 345 assertions, 1 failures, 0 errors, 0 skips
```

### サイドバーにあるマイクロポストの合計投稿数のテストを追加してみましょう。このとき、単数形のmicropostと複数形のmicropostsが正しく表示されているかどうかもテストしてください。（ヒント: [リスト 13.61](https://railstutorial.jp/chapters/user_microposts?version=7.0#code-sidebar_micropost_count)を参考にしてみてください。）
```
class MicropostSidebarTest < MicropostsInterface

  test "should display the right micropost count" do
    get root_path
    assert_match "#{@user.microposts.count} microposts", response.body
  end

  test "should user proper pluralization for zero microposts" do
    log_in_as(users(:malory))
    get root_path
    assert_match "0 microposts", response.body
  end

  test "should user proper pluralization for one micropost" do
    log_in_as(users(:lana))
    get root_path
    assert_match "1 micropost", response.body
  end
end
```

**Comment by saran12345678** [comment]
### 画像付きのマイクロポストを投稿してみましょう。画像が大きすぎますか？（次の[13.4.3](https://railstutorial.jp/chapters/user_microposts?version=7.0#sec-image_resizing)で画像サイズの問題を修正します）。
![スクリーンショット 2024-09-05 15 30 07](https://github.com/user-attachments/assets/d6023b02-5862-4a6c-ae7e-6b4c86438b9b)


### [リスト 13.67](https://railstutorial.jp/chapters/user_microposts?version=7.0#code-image_upload_test)に示すテンプレートを参考に、[13.4](https://railstutorial.jp/chapters/user_microposts?version=7.0#sec-micropost_images)で実装した画像アップローダーをテストしてください。テストの準備として、まずはターミナルで[リスト 13.66](https://railstutorial.jp/chapters/user_microposts?version=7.0#code-fixture_image)を入力し、サンプル画像をfixtureディレクトリに追加してください。継続を表すバックスラッシュ記号\は入力が必要ですが、シェルで自動的に追加される2行目冒頭の >記号は入力しないようご注意ください。[リスト 13.67](https://railstutorial.jp/chapters/user_microposts?version=7.0#code-image_upload_test)で追加したアサーションでは、Homeページにあるファイルアップロードと、投稿に成功した時に画像が表示されているかどうかをチェックしています。なお、テスト内にあるfixture_file_uploadというメソッドは、fixtureで定義されたファイルをアップロードする特別なメソッドです[22](https://railstutorial.jp/chapters/user_microposts?version=7.0#cha-13_footnote-22) 。（ヒント: image属性が有効かどうかを確かめるときは、[11.3.3](https://railstutorial.jp/chapters/account_activation?version=7.0#sec-activation_tests_and_refactoring)で紹介したassignsメソッドを使ってください。このメソッドを使うと、投稿に成功した後にcreateアクション内のマイクロポストにアクセスするようになります。）
```ruby
class ImageUploadTest < MicropostsInterface

  test "should have a file input field for images" do
    get root_path
    assert_select 'input[type=file]'
  end

  test "should be able to attach an image" do
    cont = "This micropost really ties the room together."
    img  = fixture_file_upload('kitten.jpg', 'image/jpeg')
    post microposts_path, params: { micropost: { content: cont, image: img } }
    assert assigns(:micropost).image.attached?
  end
end
```

**Comment by saran12345678** [comment]
### 5MB以上の画像ファイルを送信しようとした場合、どうなりますか?
5MBの画像を選択しても警告が出なかったため、注意が必要
![スクリーンショット 2024-09-05 16 20 06](https://github.com/user-attachments/assets/eafb2124-cf6f-49db-8eec-fbecd3298cba)

### 無効な拡張子のファイルを送信しようとした場合、どうなりますか?
そもそも無効な拡張子ファイルを選択できない。
Curlにて送ることもできるが演習の意図とは異なると判断。

**Comment by saran12345678** [comment]
### サイズの大きい画像をアップロードし、リサイズされているかどうか確認してみましょう。画像が長方形の場合も正しくリサイズされていますか?
縦横の比率は変化ない状態でリサイズされている
![スクリーンショット 2024-09-05 16 51 56](https://github.com/user-attachments/assets/e041517a-8541-470a-8d1f-3da2e11e9688)
