### ISSUE TITLE
第7章 ユーザー登録

### ISSUE THREAD

**Issue by saran12345678** [saran12345678/RubyonRailsTutorial#7]
### ブラウザで/aboutにアクセスし、デバッグ情報が表示されていることを確認してください。このページを表示するとき、どのコントローラとアクションが使われていたでしょうか?paramsの内容から確認してみましょう。
<img width="1164" alt="スクリーンショット 2024-08-30 0 53 13" src="https://github.com/user-attachments/assets/9540770f-ea92-4267-be51-440da7a15e2f">
StaticPagesControllerのaboutアクションが使われているとわかる。

### Railsコンソールを開き、データベースから最初のユーザー情報を取得し、変数userに格納してください。その後、puts user.attributes.to_yamlを実行すると何が表示されますか? ここで表示された結果と、yメソッドを使ったy user.attributesの実行結果を比較してみましょう。
```
irb(main):002> user.attributes.to_yaml
=> "---\nid: 1\nname: doby\nemail: michael@example.com\ncreated_at: !ruby/object:ActiveSupport::TimeWithZone\n  utc: 2024-08-29 12:34:15.990484000 Z\n  zone: &1 !ruby/object:ActiveSupport::TimeZone\n    name: Etc/UTC\n  time: 2024-08-29 12:34:15.990484000 Z\nupdated_at: !ruby/object:ActiveSupport::TimeWithZone\n  utc: 2024-08-29 12:41:50.194224000 Z\n  zone: *1\n  time: 2024-08-29 12:41:50.194224000 Z\npassword_digest: \"$2a$12$djFsyDpUyRPNnfMQLxrOneJUcU/xVFTCc88dSWlkGfQ6E5MT8xkNm\"\n"
irb(main):003> y user.attributes
---
id: 1
name: doby
email: michael@example.com
created_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2024-08-29 12:34:15.990484000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2024-08-29 12:34:15.990484000 Z
updated_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2024-08-29 12:41:50.194224000 Z
  zone: *1
  time: 2024-08-29 12:41:50.194224000 Z
password_digest: "$2a$12$djFsyDpUyRPNnfMQLxrOneJUcU/xVFTCc88dSWlkGfQ6E5MT8xkNm"
=> nil
```

**Comment by saran12345678** [comment]
### ERBを使って、マジックカラム（created_atとupdated_at）の値をshowページに表示してみましょう（[リスト 7.4](https://railstutorial.jp/chapters/sign_up?version=7.0#code-stub_user_view)）。
<img width="917" alt="スクリーンショット 2024-08-30 8 46 14" src="https://github.com/user-attachments/assets/7bef626a-e5ab-4ff0-8021-c8d8679700d0">

### ERBを使って、Time.nowの結果をshowページに表示してみましょう。ページを更新すると結果がどう変わるかも確認してみてください。
<img width="769" alt="スクリーンショット 2024-08-30 8 47 19" src="https://github.com/user-attachments/assets/9a534f96-7dc8-4e33-9c7f-fb0d6c450cbb">

システム日付を表示しているため、ページを更新することで時分秒が動的に変わる。
<img width="776" alt="スクリーンショット 2024-08-30 8 48 15" src="https://github.com/user-attachments/assets/44e5e148-b217-4149-9194-20f129b338cf">

**Comment by saran12345678** [comment]
### ブラウザで/aboutにアクセスし、デバッグ情報が表示されていることを確認してください。このページを表示するとき、どのコントローラとアクションが使われていたでしょうか?paramsの内容から確認してみましょう。
```
(ruby) puts param.to_yaml
--- !ruby/object:ActionController::Parameters
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  vscodeBrowserReqId: '1724976838940'
  controller: users
  action: show
  id: '1'
permitted: false
nil
```

### newアクションの中にdebuggerを差し込み、/users/newにアクセスしてみましょう。@userの内容はどのようになっているでしょうか? 確認してみてください。
```
(ruby) @user
nil
```

**Comment by saran12345678** [comment]
### （任意）Gravatar上にアカウントを作成し、あなたのメールアドレスと適当な画像を紐付けてみてください。メールアドレスをMD5ハッシュ化して、紐付けた画像がちゃんと表示されるかどうか試してみましょう。
任意のため対応せず　※メールアドレスの流出リスクを最低限に留めるため

### [リスト 7.9](https://railstutorial.jp/chapters/sign_up?version=7.0#code-gravatar_for_helper)で定義したgravatar_forヘルパーを[リスト 7.12](https://railstutorial.jp/chapters/sign_up?version=7.0#code-gravatar_option)のように変更して、sizeをオプション引数として受け取れるようにしてみましょう。正しく変更すると、例えば[リスト 7.10](https://railstutorial.jp/chapters/sign_up?version=7.0#code-user_show_with_sidebar)内ではgravatar_for @user, size: 50のように呼び出せます。重要: 改善したヘルパーはこの後の[10.3.1](https://railstutorial.jp/chapters/updating_and_deleting_users?version=7.0#sec-users_index)で実際に使うので、忘れずに実装しておきましょう。
```ruby
module UsersHelper

  # 引数で与えられたユーザのGravatar画像を返す
  def gravatar_for(user, options = { size: 80})
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end
```

### オプション引数は今でもRubyコミュニティで一般的に使われていますが「[キーワード引数（Keyword Arguments）](https://www.ruby-lang.org/ja/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/)」でも実現できます。先ほど変更した[リスト 7.12](https://railstutorial.jp/chapters/sign_up?version=7.0#code-gravatar_option)を、[リスト 7.13](https://railstutorial.jp/chapters/sign_up?version=7.0#code-gravatar_keyword)のように置き換えてもうまく動くことを確認してみましょう。この2つの実装方法はどこが違うのかを考えてみてください。
位置引数としてHashを渡すか、キーワード引数として渡すかの違い。
もう少しこれらの引数の特徴に関して掘り下げるべきではありますが、
チュートリアルを進めることを優先します。

**Comment by saran12345678** [comment]
### 試しに、[リスト 7.15](https://railstutorial.jp/chapters/sign_up?version=7.0#code-signup_form)のform_withにあるブロック変数fをすべてfoobarに置き換えてみて、結果が変わらないことを確認してみてください。確かに結果は変わりませんが、変数名をfoobarとするのはあまり良い変更ではなさそうですね。その理由について考えてみてください。
変数名が長い
変数名から何に使うのか意図を読み取れない
fはFormとしての頭文字であるはずなので、foobarとしてしまうと意味合いが変わり趣旨から逸れる。

**Comment by saran12345678** [comment]
### [『HTML編』](https://railstutorial.jp/html)ではHTMLをすべて手動で書き起こしていますが、formタグは使っていません。その理由を考えてみてください。
HTML編が有料で拝見できないため想像になりますが、
HTTPリクエストを送信するためにはHTMLであってもFormタグを使用する前提の場合、
純粋にHTML編では各種メソッド(Get,Put,Post,Deleteなど)を使用していない可能性が高い。

**Comment by saran12345678** [comment]
### /signup?admin=1にアクセスすると、paramsの中にadmin属性が含まれていることをデバッグ情報で確認してみましょう。
```
#<ActionController::Parameters {"admin"=>"1", "controller"=>"users", "action"=>"new"} permitted: false>
```

**Comment by saran12345678** [comment]
### 最小文字数を5に変更すると、エラーメッセージも自動的に更新されることを確かめてみましょう。
最小桁数変更前
![スクリーンショット 2024-08-30 18 45 57](https://github.com/user-attachments/assets/471f2f03-ca51-46fd-9ea3-98b82a2e99ec)

最小桁数を8文字から5文字に変更
```
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }
end
```

パスワードのエラーが5桁になっていることを確認
![スクリーンショット 2024-08-30 18 48 24](https://github.com/user-attachments/assets/8c2abb64-a06d-4e60-a860-1a282d8125e3)

### 未送信のユーザー登録フォーム（[図 7.14](https://railstutorial.jp/chapters/sign_up?version=7.0#fig-signup_form)）のURLと、送信済みのユーザー登録フォーム（[図 7.20](https://railstutorial.jp/chapters/sign_up?version=7.0#fig-signup_error_messages)）のURLを比べてみると、URLが違っています。その理由を考えてみてください。
GitHubのCodeSpacesはクラウド上で動いておりデプロイするごとに実行環境が構築される想定です。
そのため、毎回同じURLの場合、ランダム性がなく特定されやすい、
もしくは、実行環境が毎回変えることでスケール性を持たせているため逆に同じ環境で実行できない可能性が高い。
そのため、URLが違うと考える。

**Comment by saran12345678** [comment]
### 有効な情報を送信し、ユーザーが実際に作成されたことを、Railsコンソールを使って確認してみましょう。
Postメソッドが実行され、
最終的にトランザクションがコミットされているため、
ユーザが作成されたとわかる。
```
Started POST "/users" for 10.240.0.10 at 2024-08-30 11:16:15 +0000
Cannot render console from 10.240.0.10! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by UsersController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"name"=>"daddy", "email"=>"daddy@ccc.jp", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Create my account"}
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/users_controller.rb:15:in `create'
  User Exists? (0.2ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "daddy@ccc.jp"], ["LIMIT", 1]]
  ↳ app/controllers/users_controller.rb:15:in `create'
  User Create (2.7ms)  INSERT INTO "users" ("name", "email", "created_at", "updated_at", "password_digest") VALUES (?, ?, ?, ?, ?)  [["name", "daddy"], ["email", "daddy@ccc.jp"], ["created_at", "2024-08-30 11:16:15.584607"], ["updated_at", "2024-08-30 11:16:15.584607"], ["password_digest", "[FILTERED]"]]
  ↳ app/controllers/users_controller.rb:15:in `create'
  TRANSACTION (25.1ms)  commit transaction
  ↳ app/controllers/users_controller.rb:15:in `create'
Redirected to https://curly-fiesta-gvx96rqr57vc99p6-3000.app.github.dev/users/2
Completed 302 Found in 268ms (ActiveRecord: 28.0ms | Allocations: 6198)
```

### [リスト 7.26](https://railstutorial.jp/chapters/sign_up?version=7.0#code-user_create_action)のredirect_to @userをredirect_to user_url(@user)に書き換えても、同じ結果になることを確認してみましょう。
同じ結果(登録処理が正常に終了)になることを確認。
```ruby
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user)
    else
      render 'new', status: :unprocessable_entity
    end
  end
```
![スクリーンショット 2024-08-30 20 26 37](https://github.com/user-attachments/assets/10817876-89fe-4d0e-a154-bf8073831f0b)

**Comment by saran12345678** [comment]
### Railsコンソールを開いて、文字列内の式展開（[4.2.1](https://railstutorial.jp/chapters/rails_flavored_ruby?version=7.0#sec-strings)）でシンボルを呼び出してみましょう。例えば"#{:success}"といったコードを実行すると、どんな値が返ってきますか? 確認してみてください。
```
irb(main):001> "#{:success}"
=> "success"
```

### 上の演習で試した結果を参考に、[リスト 7.28](https://railstutorial.jp/chapters/sign_up?version=7.0#code-flash_iteration)のflashがどのような結果になるか考えてみてください。
flashに代入した値が文字列の形式として出力される。
```
irb(main):002> flash = { success: "It worked!", danger: "It failed." }
=> {:success=>"It worked!", :danger=>"It failed."}
irb(main):003> "#{flash}"
=> "{:success=>\"It worked!\", :danger=>\"It failed.\"}"
```

**Comment by saran12345678** [comment]
### Railsコンソールを使って、新しいユーザーが本当に作成されたかどうかをもう一度チェックしてみましょう。結果は、[リスト 7.30](https://railstutorial.jp/chapters/sign_up?version=7.0#code-user_created)のようになるはずです。
```
@saran12345678 ➜ /workspaces/sample_app (sign-up) $ rails c
Loading development environment (Rails 7.0.4.3)
irb(main):001> User.find_by(email: "example@railstutorial.org")
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "example@railstutorial.org"], ["LIMIT", 1]]
=> 
#<User:0x000077f27b68aef8
 id: 1,
 name: "Rails Tutorial",
 email: "example@railstutorial.org",
 created_at: Fri, 30 Aug 2024 11:51:16.502495000 UTC +00:00,
 updated_at: Fri, 30 Aug 2024 11:51:16.502495000 UTC +00:00,
 password_digest: "[FILTERED]">
```

### 自分のメールアドレスでユーザー登録を試してみましょう。既にGravatarに登録している場合、適切な画像が表示されているか確認してみてください。
前回も同様の演習があったが、メールアドレスの流出等のリスク回避のため、
この演習はスキップとする。

**Comment by saran12345678** [comment]
### [7.4.2](https://railstutorial.jp/chapters/sign_up?version=7.0#sec-the_flash)で実装したflashに対するテストを書いてみてください。どのくらい細かくテストするかはお任せします。[リスト 7.32](https://railstutorial.jp/chapters/sign_up?version=7.0#code-flash_test)に最小限のテンプレートを用意しておいたので、参考にしてください（（コードを書き込む）の部分を適切なコードに置き換えると完成します）[17](https://railstutorial.jp/chapters/sign_up?version=7.0#cha-7_footnote-17) 。
注釈を参考に、flashがnilではないことのみを確認する。
```
    assert_not flash.empty?
```

### 本文中でも指摘したように、flash用のHTML（[リスト 7.29](https://railstutorial.jp/chapters/sign_up?version=7.0#code-layout_flash)）は読みにくくなってしまっています。これを、より読みやすくした[リスト 7.33](https://railstutorial.jp/chapters/sign_up?version=7.0#code-layout_flash_content_tag)のコードに変更してみましょう。変更が終わったらテストスイートを実行し、正常に動作することを確認してください。なお、このコードでは、Railsのcontent_tagというヘルパーを使っています。
指示通りにコードを変更。
```
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
```

### [リスト 7.26](https://railstutorial.jp/chapters/sign_up?version=7.0#code-user_create_action)のリダイレクトの行をコメントアウトすると、テストが失敗することを確認してみましょう。
テストに失敗することを確認。
```
  1) Error:
UsersSignupTest#test_valid_signup_information:
RuntimeError: not a redirect! 204 No Content
    test/integration/users_signup_test.rb:27:in `block in <class:UsersSignupTest>'

21 runs, 47 assertions, 0 failures, 1 errors, 0 skips
```

### [リスト 7.26](https://railstutorial.jp/chapters/sign_up?version=7.0#code-user_create_action)で、@user.saveの部分をfalseに置き換えたとしましょう（バグを埋め込んでしまったと仮定してください）。このとき、assert_differenceのテストではどのようにしてこのバグを検知するでしょうか? テストコードを追って考えてみてください。
createのメソッドにて、登録処理を行わなくなり、
また、Falseに固定されるため登録処理は必ず失敗することになる。
その場合登録失敗のテストは、UserのCountに変わりがないため、テストに失敗する。
一方、登録成功のテストはUserのCountが変わらないため、テストエラーとなりバグを検知できる。

**Comment by saran12345678** [comment]
### ブラウザから本番環境にアクセスし、TLSが有効になっているか、URLがhttpsになっているかどうかを確認してみましょう。
保護されていることを確認
![スクリーンショット 2024-08-30 21 45 56](https://github.com/user-attachments/assets/d27752bf-bd2e-4bec-b5ea-b2211c4b08ab)


### 本番環境でユーザーを作成してみましょう。Gravatarの画像は正しく表示されているでしょうか?
メールアドレスに紐づいているGravatarの画像がきちんと表示されていることを確認
![スクリーンショット 2024-08-30 21 48 52](https://github.com/user-attachments/assets/21abe55f-da34-4bf9-b9f3-676b41f96c6c)
